function New-GenerateCSVReportScript {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory)]
        [string]$BaseName,

        [Parameter(Mandatory)]
        [array]$Groups,

        [switch]$ReuseExisting
    )

    $safeName = ($BaseName -replace '[^a-zA-Z0-9 ]','').Trim().Replace(' ', '-')

    # Choose script path based on existence + ReuseExisting behavior
    $toolRoot   = Get-GratBoxRoot
    $scriptsDir = Join-Path $toolRoot 'Scripts'
    if (-not (Test-Path $scriptsDir)) { New-Item -ItemType Directory -Force -Path $scriptsDir | Out-Null }

    $basePath   = Join-Path $scriptsDir "Run-$safeName-Reports.ps1"

    if (Test-Path $basePath) {

        if ($ReuseExisting) {
            # Canonical behavior—update existing script
            Write-Warning "CSV report script exists. -ReuseExisting specified, updating existing script:"
            Write-Warning $basePath
            $scriptPath = $basePath
        }
        else {
            # Interactive choice—timestamped copy (safe default) vs overwrite
            $choice = Read-Host "CSV report script exists. Update existing (overwrite)(Y/N) (default: N)"
            if ($choice -and $choice.ToUpper().StartsWith('Y')) {
                Write-Warning "Updating existing CSV report script (overwrite):"
                Write-Warning $basePath
                $scriptPath = $basePath
            }
            else {
                $timestamp  = Get-Date -Format "yyyyMMdd-HHmmss"
                $scriptPath = (Join-Path $scriptsDir "Run-$safeName-Reports-$timestamp.ps1")
                Write-Warning "Creating timestamped CSV report script:"
                Write-Warning $scriptPath
            }
        }
    }
    else {
        $scriptPath = $basePath
    }

    Write-Host "[INFO] Creating CSV report script: $scriptPath" -ForegroundColor Cyan

    $content = @()
    $content += "# Auto-generated by New-GratBoxMigrationWaveSet"
    $content += "# Created: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    $content += ""
    $content += '$groups = @('

    foreach ($g in $Groups) {
        $content += "    @{ Id = `"$($g.Id)`"; Name = `"$($g.Name)`" },"
    }

    # Remove trailing comma (if we added at least one group)
    if ($Groups.Count -gt 0) {
        $content[-1] = $content[-1].TrimEnd(',')
    }

    $content += ")"
    $content += ""
    $content += @'
foreach ($g in $groups) {
    Write-Host "==============================================="
    Write-Host "Starting export for: $($g.Name)"
    Write-Host "GroupId : $($g.Id)"
    Write-Host "==============================================="

    export-intuneManagedDevicesFromGroup `
        -GroupId $g.Id `
        -GroupName $g.Name `
        -StrictMdMOnly

    Write-Host "Finished export for: $($g.Name)"
    Write-Host ""
}
'@

    Set-Content -Path $scriptPath -Value $content -Encoding UTF8

    Write-Host "[OK] Script created/updated: $scriptPath" -ForegroundColor Green
}
